TEAM_MAPPING = {
    "ana": "Anaheim Ducks",
    "ari": "Arizona Coyotes",
    "bos": "Boston Bruins",
    "buf": "Buffalo Sabres",
    "cgy": "Calgary Flames",
    "car": "Carolina Hurricanes",
    "chi": "Chicago Blackhawks",
    "col": "Colorado Avalanche",
    "cbj": "Columbus Blue Jackets",
    "dal": "Dallas Stars",
    "det": "Detroit Red Wings",
    "edm": "Edmonton Oilers",
    "fla": "Florida Panthers",
    "lak": "Los Angeles Kings",
    "min": "Minnesota Wild",
    "mtl": "Montreal Canadiens",
    "nsh": "Nashville Predators",
    "njd": "New Jersey Devils",
    "nyi": "New York Islanders",
    "nyr": "New York Rangers",
    "ott": "Ottawa Senators",
    "phi": "Philadelphia Flyers",
    "pit": "Pittsburgh Penguins",
    "sea": "Seattle Kraken",
    "sjs": "San Jose Sharks",
    "stl": "St. Louis Blues",
    "tbl": "Tampa Bay Lightning",
    "tor": "Toronto Maple Leafs",
    "van": "Vancouver Canucks",
    "vgk": "Vegas Golden Knights",
    "wsh": "Washington Capitals",
    "wpg": "Winnipeg Jets"
}